# Generated by Django 5.2.7 on 2026-05-07 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_reservation_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rooms/', verbose_name='Изображение')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='meeting_reservation_system.room', verbose_name='Комната')),
            ],
            options={
                'verbose_name': 'Дополнительное фото комнаты',
                'verbose_name_plural': 'Дополнительные фото комнат',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
