# Generated by Django 5.2.12 on 2026-05-12 06:37

from django.db import migrations, models


def forwards_sync_equipment(apps, schema_editor):
    Room = apps.get_model('meeting_reservation_system', 'Room')
    Equipment = apps.get_model('meeting_reservation_system', 'Equipment')

    through_model = Room.equipment_items.through
    equipment_by_key = {
        equipment.name.strip().casefold(): equipment
        for equipment in Equipment.objects.all()
        if equipment.name and equipment.name.strip()
    }

    for room in Room.objects.all():
        raw_items = [
            item.strip()
            for item in (room.equipment or '').splitlines()
            if item and item.strip()
        ]
        if not raw_items:
            continue

        seen_keys = set()
        for item_name in raw_items:
            item_key = item_name.casefold()
            if item_key in seen_keys:
                continue
            seen_keys.add(item_key)

            equipment = equipment_by_key.get(item_key)
            if equipment is None:
                categories = [room.category] if room.category else []
                equipment = Equipment.objects.create(
                    name=item_name,
                    categories=categories,
                    is_active=True,
                )
                equipment_by_key[item_key] = equipment
            elif room.category and room.category not in (equipment.categories or []):
                equipment.categories = [*(equipment.categories or []), room.category]
                equipment.save(update_fields=['categories'])

            through_model.objects.get_or_create(
                room_id=room.id,
                equipment_id=equipment.id,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_reservation_system', '0002_roomimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название')),
                ('categories', models.JSONField(blank=True, default=list, verbose_name='Категории комнат')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='room',
            name='equipment_items',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='meeting_reservation_system.equipment', verbose_name='Справочник оборудования'),
        ),
        migrations.RunPython(forwards_sync_equipment, migrations.RunPython.noop),
    ]
