# Generated by Django 5.2.12 on 2026-05-12 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_reservation_system', '0003_equipment_room_equipment_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Владелец'), ('admin', 'Администратор'), ('manager', 'Менеджер'), ('user', 'Пользователь')], default='user', max_length=10),
        ),
    ]
