# Generated by Django 5.2.12 on 2026-05-13 06:49

from django.db import migrations, models


def seed_default_info_blocks(apps, schema_editor):
    InfoBlock = apps.get_model('meeting_reservation_system', 'InfoBlock')

    if InfoBlock.objects.exists():
        return

    InfoBlock.objects.bulk_create([
        InfoBlock(
            section='general',
            title='',
            content=(
                'Система бронирования переговоров предназначена для сотрудников компании, '
                'а также и для обычных людей, которым надо обсудить деловые вещи. '
                'Здесь вы можете забронировать переговорку для встреч, презентаций и других мероприятий.'
            ),
            order=10,
            is_active=True,
        ),
        InfoBlock(
            section='rules',
            title='⏱️ Время бронирования',
            content='Максимальное время бронирования - 4 часа подряд',
            order=10,
            is_active=True,
        ),
        InfoBlock(
            section='rules',
            title='📅 Планирование',
            content='Бронируйте комнаты минимум за 2 часа до начала встречи',
            order=20,
            is_active=True,
        ),
        InfoBlock(
            section='rules',
            title='🔒 Ответственность',
            content='Вы несете ответственность за сохранность оборудования в комнате',
            order=30,
            is_active=True,
        ),
        InfoBlock(
            section='rules',
            title='❌ Отмена брони',
            content='Отменяйте бронь как минимум за 2 часа до начала, если планы изменились',
            order=40,
            is_active=True,
        ),
        InfoBlock(
            section='instructions',
            title='',
            content='Выберите подходящую переговорную комнату из списка',
            order=10,
            is_active=True,
        ),
        InfoBlock(
            section='instructions',
            title='',
            content='Нажмите "Забронировать" и выберите дату и время',
            order=20,
            is_active=True,
        ),
        InfoBlock(
            section='instructions',
            title='',
            content='Введите контактные данные и далее нажмите "Забронировать"',
            order=30,
            is_active=True,
        ),
        InfoBlock(
            section='instructions',
            title='',
            content='Ожидайте подтверждения от менеджера, вся информация придет на вашу почту',
            order=40,
            is_active=True,
        ),
        InfoBlock(
            section='instructions',
            title='',
            content='Приходите в назначенное время',
            order=50,
            is_active=True,
        ),
        InfoBlock(
            section='contacts',
            title='📧 Email',
            content='testsite9356@gmail.com',
            order=10,
            is_active=True,
        ),
        InfoBlock(
            section='contacts',
            title='📞 Телефон',
            content='+7 (993) 939-03-31',
            order=20,
            is_active=True,
        ),
        InfoBlock(
            section='contacts',
            title='🕐 Время работы',
            content='Пн-Пт: 9:00-23:00',
            order=30,
            is_active=True,
        ),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_reservation_system', '0004_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('general', '📋 Общая информация'), ('rules', '📝 Правила бронирования'), ('instructions', '📖 Инструкция по бронированию'), ('contacts', '📞 Контакты поддержки')], default='general', max_length=20, verbose_name='Раздел')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Текст')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Блок информации',
                'verbose_name_plural': 'Блоки информации',
                'ordering': ['section', 'order', 'id'],
            },
        ),
        migrations.RunPython(seed_default_info_blocks, migrations.RunPython.noop),
    ]
