# Generated by Django 5.2.12 on 2026-05-13 07:35

from django.db import migrations, models


def seed_default_categories_and_sections(apps, schema_editor):
    FAQCategory = apps.get_model('meeting_reservation_system', 'FAQCategory')
    InfoSection = apps.get_model('meeting_reservation_system', 'InfoSection')

    faq_categories = [
        {'name': 'Общее', 'slug': 'general', 'order': 1, 'is_active': True},
        {'name': 'Бронирование', 'slug': 'booking', 'order': 2, 'is_active': True},
        {'name': 'Оплата', 'slug': 'payment', 'order': 3, 'is_active': True},
        {'name': 'Технические вопросы', 'slug': 'technical', 'order': 4, 'is_active': True},
    ]

    info_sections = [
        {
            'name': 'Общая информация',
            'slug': 'general',
            'order': 1,
            'description': 'Краткие пояснения о работе системы и офисов.',
            'is_active': True,
        },
        {
            'name': 'Правила бронирования',
            'slug': 'rules',
            'order': 2,
            'description': 'Что можно и что нельзя делать при бронировании комнат.',
            'is_active': True,
        },
        {
            'name': 'Инструкции',
            'slug': 'instructions',
            'order': 3,
            'description': 'Пошаговый сценарий бронирования и действий на сайте.',
            'is_active': True,
        },
        {
            'name': 'Контакты поддержки',
            'slug': 'contacts',
            'order': 4,
            'description': 'Как связаться с поддержкой и в какие часы она работает.',
            'is_active': True,
        },
    ]

    for spec in faq_categories:
        FAQCategory.objects.update_or_create(slug=spec['slug'], defaults=spec)

    for spec in info_sections:
        InfoSection.objects.update_or_create(slug=spec['slug'], defaults=spec)


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_reservation_system', '0005_infoblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='Slug')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Категория FAQ',
                'verbose_name_plural': 'Категории FAQ',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InfoSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('slug', models.SlugField(max_length=80, unique=True, verbose_name='Slug')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Раздел информации',
                'verbose_name_plural': 'Разделы информации',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.CharField(default='general', max_length=80),
        ),
        migrations.AlterField(
            model_name='infoblock',
            name='section',
            field=models.CharField(default='general', max_length=80, verbose_name='Раздел'),
        ),
        migrations.RunPython(seed_default_categories_and_sections, migrations.RunPython.noop),
    ]
